// Code generated by swagger-to-go. DO NOT EDIT.
package userpb

import (
	"encoding/json"

	"github.com/fzerorubigd/balloon/pkg/assert"
	"github.com/fzerorubigd/balloon/pkg/grpcgw"
)

const paths = "{\"/v1/login\":{\"post\":{\"operationId\":\"Login\",\"parameters\":[{\"in\":\"body\",\"name\":\"body\",\"required\":true,\"schema\":{\"$ref\":\"#/definitions/userLoginRequest\"}}],\"responses\":{\"200\":{\"description\":\"\",\"schema\":{\"$ref\":\"#/definitions/userUser\"}}},\"tags\":[\"UserSystem\"]}},\"/v1/logout\":{\"get\":{\"operationId\":\"Logout\",\"responses\":{\"200\":{\"description\":\"\",\"schema\":{\"$ref\":\"#/definitions/userNoopResponse\"}}},\"tags\":[\"UserSystem\"]}}}"
const definitions = "{\"UserStatus\":{\"default\":\"USER_STATUS_INVALID\",\"enum\":[\"USER_STATUS_INVALID\",\"USER_STATUS_REGISTERED\",\"USER_STATUS_ACTIVE\",\"USER_STATUS_BANNED\"],\"type\":\"string\"},\"userLoginRequest\":{\"properties\":{\"password\":{\"type\":\"string\"},\"username\":{\"type\":\"string\"}},\"type\":\"object\"},\"userNoopResponse\":{\"type\":\"object\"},\"userUser\":{\"properties\":{\"email\":{\"type\":\"string\"},\"id\":{\"format\":\"int64\",\"type\":\"string\"},\"status\":{\"$ref\":\"#/definitions/UserStatus\"},\"username\":{\"type\":\"string\"}},\"type\":\"object\"}}"

func init() {
	var (
		p = make(map[string]interface{})
		d = make(map[string]interface{})
	)

	assert.Nil(json.Unmarshal([]byte(paths), &p))
	assert.Nil(json.Unmarshal([]byte(definitions), &d))

	grpcgw.RegisterSwagger(p, d)
}

