// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: modules/user/proto/user.proto

package userpb

import (
	fmt "fmt"

	proto "github.com/golang/protobuf/proto"

	math "math"

	"github.com/fzerorubigd/balloon/pkg/postgres/model"
	_ "github.com/fzerorubigd/protobuf/extra"
	_ "github.com/gogo/protobuf/gogoproto"

	_ "github.com/gogo/protobuf/types"

	_ "google.golang.org/genproto/googleapis/api/annotations"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

const (
	// UserSchema is the User module schema
	UserSchema = "aaa"
	// UserTable is the User table name
	UserTable = "users"
	// UserTableFull is the User table name with schema
	UserTableFull = UserSchema + "." + UserTable
)

// Manager is the model manager for aaa package
type Manager struct {
	model.Manager
}

// NewAaaManager create and return a manager for this module
func NewManager() *Manager {
	return &Manager{}
}

// NewAaaManagerFromTransaction create and return a manager for this module from a transaction
func NewManagerFromTransaction(tx model.DBX) (*Manager, error) {
	m := &Manager{}
	err := m.Hijack(tx)
	if err != nil {
		return nil, err
	}

	return m, nil
}

/*
&"aaa"
proto: missing extension
proto: nil *descriptor.MessageOptions is not extendable
proto: nil *descriptor.MessageOptions is not extendable
proto: nil *descriptor.MessageOptions is not extendable
*/
