// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: modules/user/proto/user.proto

package userpb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/fzerorubigd/protobuf/extra"
import _ "github.com/gogo/protobuf/gogoproto"
import types "github.com/gogo/protobuf/types"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type UserStatus int32

const (
	UserStatus_USER_STATUS_INVALID    UserStatus = 0
	UserStatus_USER_STATUS_REGISTERED UserStatus = 1
	UserStatus_USER_STATUS_ACTIVE     UserStatus = 2
	UserStatus_USER_STATUS_BANNED     UserStatus = 3
)

var UserStatus_name = map[int32]string{
	0: "USER_STATUS_INVALID",
	1: "USER_STATUS_REGISTERED",
	2: "USER_STATUS_ACTIVE",
	3: "USER_STATUS_BANNED",
}
var UserStatus_value = map[string]int32{
	"USER_STATUS_INVALID":    0,
	"USER_STATUS_REGISTERED": 1,
	"USER_STATUS_ACTIVE":     2,
	"USER_STATUS_BANNED":     3,
}

func (x UserStatus) String() string {
	return proto.EnumName(UserStatus_name, int32(x))
}
func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_user_1a40cdad496e1ed3, []int{0}
}

type User struct {
	Id                   int64            `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" db:"id" `
	Email                string           `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty" db:"email" `
	Password             string           `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty" db:"password" `
	Status               UserStatus       `protobuf:"varint,4,opt,name=status,proto3,enum=user.UserStatus" json:"status,omitempty" db:"status" `
	CreatedAt            *types.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" db:"created_at" `
	UpdatedAt            *types.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" db:"updated_at" `
	LastLogin            *types.Timestamp `protobuf:"bytes,7,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty" db:"last_login" `
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_1a40cdad496e1ed3, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetStatus() UserStatus {
	if m != nil {
		return m.Status
	}
	return UserStatus_USER_STATUS_INVALID
}

func (m *User) GetCreatedAt() *types.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *types.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *User) GetLastLogin() *types.Timestamp {
	if m != nil {
		return m.LastLogin
	}
	return nil
}

type UserResponse struct {
	Id                   int64      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string     `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Token                string     `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Status               UserStatus `protobuf:"varint,4,opt,name=status,proto3,enum=user.UserStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_1a40cdad496e1ed3, []int{1}
}
func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (dst *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(dst, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *UserResponse) GetStatus() UserStatus {
	if m != nil {
		return m.Status
	}
	return UserStatus_USER_STATUS_INVALID
}

type LoginRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty" validate:"email,required" `
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty" validate:"gte=6,required" `
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_1a40cdad496e1ed3, []int{2}
}
func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (dst *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(dst, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LogoutRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutRequest) Reset()         { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()    {}
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_1a40cdad496e1ed3, []int{3}
}
func (m *LogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRequest.Unmarshal(m, b)
}
func (m *LogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRequest.Marshal(b, m, deterministic)
}
func (dst *LogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRequest.Merge(dst, src)
}
func (m *LogoutRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutRequest.Size(m)
}
func (m *LogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRequest proto.InternalMessageInfo

type LogoutResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutResponse) Reset()         { *m = LogoutResponse{} }
func (m *LogoutResponse) String() string { return proto.CompactTextString(m) }
func (*LogoutResponse) ProtoMessage()    {}
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_1a40cdad496e1ed3, []int{4}
}
func (m *LogoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutResponse.Unmarshal(m, b)
}
func (m *LogoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutResponse.Marshal(b, m, deterministic)
}
func (dst *LogoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutResponse.Merge(dst, src)
}
func (m *LogoutResponse) XXX_Size() int {
	return xxx_messageInfo_LogoutResponse.Size(m)
}
func (m *LogoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutResponse proto.InternalMessageInfo

type RegisterRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty" validate:"email,required" `
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty" validate:"gte=6,required" `
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_1a40cdad496e1ed3, []int{5}
}
func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (dst *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(dst, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type PingRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_1a40cdad496e1ed3, []int{6}
}
func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (dst *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(dst, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

type ChangePasswordRequest struct {
	OldPassword          string   `protobuf:"bytes,1,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty" validate:"gte=6,required" `
	NewPassword          string   `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty" validate:"gte=6,required" `
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordRequest) Reset()         { *m = ChangePasswordRequest{} }
func (m *ChangePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordRequest) ProtoMessage()    {}
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_1a40cdad496e1ed3, []int{7}
}
func (m *ChangePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordRequest.Unmarshal(m, b)
}
func (m *ChangePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordRequest.Marshal(b, m, deterministic)
}
func (dst *ChangePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordRequest.Merge(dst, src)
}
func (m *ChangePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordRequest.Size(m)
}
func (m *ChangePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordRequest proto.InternalMessageInfo

func (m *ChangePasswordRequest) GetOldPassword() string {
	if m != nil {
		return m.OldPassword
	}
	return ""
}

func (m *ChangePasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type ChangePasswordResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordResponse) Reset()         { *m = ChangePasswordResponse{} }
func (m *ChangePasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordResponse) ProtoMessage()    {}
func (*ChangePasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_1a40cdad496e1ed3, []int{8}
}
func (m *ChangePasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordResponse.Unmarshal(m, b)
}
func (m *ChangePasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordResponse.Marshal(b, m, deterministic)
}
func (dst *ChangePasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordResponse.Merge(dst, src)
}
func (m *ChangePasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordResponse.Size(m)
}
func (m *ChangePasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*UserResponse)(nil), "user.UserResponse")
	proto.RegisterType((*LoginRequest)(nil), "user.LoginRequest")
	proto.RegisterType((*LogoutRequest)(nil), "user.LogoutRequest")
	proto.RegisterType((*LogoutResponse)(nil), "user.LogoutResponse")
	proto.RegisterType((*RegisterRequest)(nil), "user.RegisterRequest")
	proto.RegisterType((*PingRequest)(nil), "user.PingRequest")
	proto.RegisterType((*ChangePasswordRequest)(nil), "user.ChangePasswordRequest")
	proto.RegisterType((*ChangePasswordResponse)(nil), "user.ChangePasswordResponse")
	proto.RegisterEnum("user.UserStatus", UserStatus_name, UserStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserSystemClient is the client API for UserSystem service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserSystemClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*UserResponse, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*UserResponse, error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*UserResponse, error)
	ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error)
}

type userSystemClient struct {
	cc *grpc.ClientConn
}

func NewUserSystemClient(cc *grpc.ClientConn) UserSystemClient {
	return &userSystemClient{cc}
}

func (c *userSystemClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/user.UserSystem/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSystemClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, "/user.UserSystem/Logout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSystemClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/user.UserSystem/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSystemClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/user.UserSystem/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSystemClient) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error) {
	out := new(ChangePasswordResponse)
	err := c.cc.Invoke(ctx, "/user.UserSystem/ChangePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserSystemServer is the server API for UserSystem service.
type UserSystemServer interface {
	Login(context.Context, *LoginRequest) (*UserResponse, error)
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	Register(context.Context, *RegisterRequest) (*UserResponse, error)
	Ping(context.Context, *PingRequest) (*UserResponse, error)
	ChangePassword(context.Context, *ChangePasswordRequest) (*ChangePasswordResponse, error)
}

func RegisterUserSystemServer(s *grpc.Server, srv UserSystemServer) {
	s.RegisterService(&_UserSystem_serviceDesc, srv)
}

func _UserSystem_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSystemServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserSystem/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSystemServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSystem_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSystemServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserSystem/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSystemServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSystem_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSystemServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserSystem/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSystemServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSystem_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSystemServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserSystem/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSystemServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSystem_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSystemServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserSystem/ChangePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSystemServer).ChangePassword(ctx, req.(*ChangePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserSystem_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserSystem",
	HandlerType: (*UserSystemServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _UserSystem_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _UserSystem_Logout_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _UserSystem_Register_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _UserSystem_Ping_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _UserSystem_ChangePassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "modules/user/proto/user.proto",
}

func init() { proto.RegisterFile("modules/user/proto/user.proto", fileDescriptor_user_1a40cdad496e1ed3) }

var fileDescriptor_user_1a40cdad496e1ed3 = []byte{
	// 838 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x54, 0xbf, 0x6f, 0x23, 0x45,
	0x14, 0xbe, 0xb5, 0x63, 0x93, 0x8c, 0x1d, 0x7b, 0x33, 0xc9, 0x85, 0xcd, 0x5e, 0x0e, 0xaf, 0x46,
	0x02, 0xac, 0x08, 0xbc, 0xba, 0x80, 0x28, 0x2c, 0x51, 0xd8, 0x17, 0x0b, 0x82, 0xa2, 0x60, 0xad,
	0x9d, 0x2b, 0x68, 0xac, 0xb1, 0x77, 0x6e, 0x6f, 0xc5, 0x7a, 0x67, 0xb3, 0x33, 0x7b, 0x01, 0x2a,
	0x04, 0xdd, 0xb5, 0xd4, 0xfc, 0x0d, 0x48, 0x74, 0x54, 0xb4, 0xf4, 0x74, 0x14, 0xae, 0xf8, 0x03,
	0x22, 0xff, 0x05, 0x68, 0x66, 0xf6, 0x57, 0x22, 0x4b, 0x84, 0x8a, 0xc6, 0x9a, 0x79, 0xef, 0x7d,
	0xdf, 0xfb, 0xe6, 0xbd, 0xcf, 0x0b, 0x9e, 0x2e, 0xa9, 0x9b, 0x04, 0x84, 0xd9, 0x09, 0x23, 0xb1,
	0x1d, 0xc5, 0x94, 0x53, 0x79, 0xec, 0xc9, 0x23, 0xdc, 0x12, 0x67, 0xf3, 0x99, 0xe7, 0xf3, 0x57,
	0xc9, 0xbc, 0xb7, 0xa0, 0x4b, 0xfb, 0xe5, 0x77, 0x24, 0xa6, 0x71, 0x32, 0xf7, 0x3d, 0x57, 0x95,
	0xcf, 0x93, 0x97, 0x36, 0xf9, 0x86, 0xc7, 0x58, 0xfd, 0x2a, 0xa0, 0xf9, 0x61, 0x09, 0xe2, 0x51,
	0x8f, 0x16, 0xb5, 0xe2, 0xa6, 0xfa, 0x88, 0x53, 0x5a, 0x7e, 0xec, 0x51, 0xea, 0x05, 0xc4, 0xc6,
	0x91, 0x6f, 0xe3, 0x30, 0xa4, 0x1c, 0x73, 0x9f, 0x86, 0x2c, 0xcd, 0x76, 0xd2, 0x6c, 0xce, 0xc1,
	0xfd, 0x25, 0x61, 0x1c, 0x2f, 0x23, 0x55, 0x80, 0x7e, 0xab, 0x82, 0xad, 0x2b, 0x46, 0x62, 0x78,
	0x0c, 0x2a, 0xbe, 0x6b, 0x68, 0x96, 0xd6, 0xad, 0x0e, 0x9b, 0xeb, 0x55, 0x67, 0xdb, 0x9d, 0xf7,
	0x91, 0xef, 0x22, 0xcb, 0xa9, 0xf8, 0x2e, 0x7c, 0x17, 0xd4, 0xc8, 0x12, 0xfb, 0x81, 0x51, 0xb1,
	0xb4, 0xee, 0xce, 0xb0, 0xbd, 0x5e, 0x75, 0x1a, 0xa2, 0x40, 0x06, 0x91, 0xe5, 0xa8, 0x2c, 0xec,
	0x81, 0xed, 0x08, 0x33, 0x76, 0x43, 0x63, 0xd7, 0xa8, 0xca, 0x4a, 0xb8, 0x5e, 0x75, 0x5a, 0xa2,
	0x32, 0x8b, 0x23, 0xcb, 0xc9, 0x6b, 0x60, 0x1f, 0xd4, 0x19, 0xc7, 0x3c, 0x61, 0xc6, 0x96, 0xa5,
	0x75, 0x5b, 0xa7, 0x7a, 0x4f, 0x4e, 0x50, 0x08, 0x9a, 0xc8, 0xf8, 0x50, 0x5f, 0xaf, 0x3a, 0x4d,
	0x81, 0x57, 0x75, 0xc8, 0x72, 0x52, 0x04, 0xfc, 0x12, 0x80, 0x45, 0x4c, 0x30, 0x27, 0xee, 0x0c,
	0x73, 0xa3, 0x66, 0x69, 0xdd, 0xc6, 0xa9, 0xd9, 0x53, 0xef, 0xed, 0x65, 0xef, 0xed, 0x4d, 0xb3,
	0xf7, 0x0e, 0x0f, 0xd6, 0xab, 0x8e, 0x2e, 0x98, 0x0a, 0x14, 0xb2, 0x9c, 0x9d, 0xf4, 0x36, 0xe0,
	0x82, 0x30, 0x89, 0xdc, 0x8c, 0xb0, 0xfe, 0x70, 0xc2, 0x02, 0x25, 0x08, 0xd3, 0x9b, 0x22, 0x0c,
	0x30, 0xe3, 0xb3, 0x80, 0x7a, 0x7e, 0x68, 0xbc, 0xf5, 0x70, 0xc2, 0x02, 0x25, 0x08, 0xc5, 0xed,
	0x42, 0x5c, 0xfa, 0xbb, 0x7f, 0xdc, 0x1e, 0x69, 0x7f, 0xdd, 0x1e, 0xd5, 0xc4, 0x94, 0x18, 0xe2,
	0xa0, 0x29, 0x26, 0xe5, 0x10, 0x16, 0xd1, 0x90, 0x11, 0xd8, 0x2a, 0x56, 0x28, 0x97, 0x76, 0x70,
	0x67, 0x69, 0xd9, 0x8e, 0x0e, 0x40, 0x8d, 0xd3, 0xaf, 0x49, 0xa8, 0x16, 0xe4, 0xa8, 0x0b, 0xec,
	0xfe, 0xdb, 0x26, 0xb2, 0xb9, 0xa3, 0xef, 0x35, 0xd0, 0x94, 0x72, 0x1c, 0x72, 0x9d, 0x10, 0xc6,
	0xe1, 0xc7, 0x59, 0x1b, 0x4d, 0x6e, 0xfc, 0x9d, 0xf5, 0xaa, 0x63, 0xbe, 0xc6, 0x81, 0x2f, 0xc6,
	0x90, 0x3a, 0xe4, 0x83, 0x98, 0x5c, 0x27, 0x7e, 0x4c, 0xdc, 0xc2, 0x2a, 0xfd, 0x92, 0x55, 0x2a,
	0x9b, 0x80, 0x1e, 0x27, 0x9f, 0x7e, 0x52, 0x06, 0xe6, 0xf5, 0xa8, 0x0d, 0x76, 0x2f, 0xa8, 0x47,
	0x13, 0x9e, 0x4a, 0x40, 0x3a, 0x68, 0x65, 0x01, 0x35, 0x0b, 0xf4, 0xa3, 0x06, 0xda, 0x0e, 0xf1,
	0x7c, 0xc6, 0xc5, 0x80, 0xfe, 0x2f, 0xa1, 0xbb, 0xa0, 0x31, 0xf6, 0x43, 0x2f, 0x93, 0xf9, 0xb3,
	0x06, 0x1e, 0x3f, 0x7f, 0x85, 0x43, 0x8f, 0x8c, 0xd3, 0x8a, 0x4c, 0xda, 0x00, 0x34, 0x69, 0xe0,
	0xce, 0xf2, 0x46, 0xda, 0x83, 0x1a, 0x35, 0x68, 0xe0, 0x66, 0x4c, 0x82, 0x22, 0x24, 0x37, 0xb3,
	0xff, 0xa8, 0xb5, 0x11, 0x92, 0x9b, 0x8c, 0x02, 0x19, 0xe0, 0xf0, 0xbe, 0x3c, 0x35, 0xce, 0x93,
	0x6b, 0x00, 0x0a, 0x2b, 0xc0, 0xb7, 0xc1, 0xfe, 0xd5, 0x64, 0xe4, 0xcc, 0x26, 0xd3, 0xc1, 0xf4,
	0x6a, 0x32, 0x3b, 0xbf, 0x7c, 0x31, 0xb8, 0x38, 0x3f, 0xd3, 0x1f, 0x41, 0x13, 0x1c, 0x96, 0x13,
	0xce, 0xe8, 0xb3, 0xf3, 0xc9, 0x74, 0xe4, 0x8c, 0xce, 0x74, 0x0d, 0x1e, 0x02, 0x58, 0xce, 0x0d,
	0x9e, 0x4f, 0xcf, 0x5f, 0x8c, 0xf4, 0xca, 0xfd, 0xf8, 0x70, 0x70, 0x79, 0x39, 0x3a, 0xd3, 0xab,
	0xa7, 0xbf, 0x57, 0xd3, 0x9e, 0xdf, 0x32, 0x4e, 0x96, 0xf0, 0x0b, 0x50, 0x93, 0xae, 0x83, 0x50,
	0x39, 0xb3, 0x6c, 0x41, 0x13, 0x16, 0x6e, 0xcd, 0x1d, 0x70, 0xf4, 0xc3, 0x9f, 0x7f, 0xff, 0x54,
	0xd9, 0x47, 0x2d, 0xfb, 0xf5, 0x33, 0xf5, 0x8d, 0x96, 0xff, 0xa8, 0xbe, 0x76, 0x02, 0xc7, 0xa0,
	0xae, 0xec, 0x02, 0xf7, 0x73, 0xb2, 0xc2, 0x4d, 0xe6, 0xc1, 0xdd, 0x60, 0xca, 0xf7, 0xe4, 0xcd,
	0x2f, 0xe6, 0x23, 0xc9, 0xb9, 0x07, 0xdb, 0x65, 0x4e, 0xc1, 0x33, 0x01, 0xdb, 0x99, 0xdb, 0xe0,
	0x63, 0x05, 0xbf, 0xe7, 0xbe, 0x8d, 0x1a, 0x8f, 0x25, 0xdf, 0x21, 0xda, 0xcb, 0xf9, 0xe2, 0x14,
	0x25, 0x64, 0x7e, 0x0e, 0xb6, 0x84, 0x7b, 0xe0, 0x9e, 0x42, 0x96, 0x9c, 0xb4, 0xf9, 0xc1, 0xb9,
	0xc0, 0x36, 0xdc, 0xcd, 0x09, 0x23, 0xc1, 0xc0, 0x41, 0xeb, 0xee, 0x62, 0xe1, 0x13, 0x45, 0xb0,
	0xd1, 0x8d, 0xe6, 0xf1, 0xe6, 0x64, 0xda, 0xe7, 0xfd, 0xbc, 0xcf, 0x53, 0x64, 0xe4, 0x7d, 0x16,
	0xb2, 0xd8, 0xce, 0xec, 0xd7, 0xd7, 0x4e, 0x86, 0xef, 0xbd, 0xf9, 0xf5, 0xa8, 0x8a, 0x31, 0x06,
	0xdb, 0x0b, 0xba, 0x94, 0x94, 0xc3, 0x1d, 0xa1, 0x78, 0x2c, 0x3e, 0x7d, 0x63, 0xed, 0xab, 0xba,
	0x08, 0x45, 0xf3, 0x79, 0x5d, 0x7e, 0x0b, 0x3f, 0xfa, 0x27, 0x00, 0x00, 0xff, 0xff, 0x9c, 0xc0,
	0xbb, 0x51, 0x52, 0x07, 0x00, 0x00,
}
