// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: modules/user/proto/user.proto

package userpb

import (
	context "context"
	fmt "fmt"
	_ "github.com/fzerorubigd/protobuf/extra"
	types "github.com/fzerorubigd/protobuf/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type UserStatus int32

const (
	UserStatus_USER_STATUS_INVALID    UserStatus = 0
	UserStatus_USER_STATUS_REGISTERED UserStatus = 1
	UserStatus_USER_STATUS_ACTIVE     UserStatus = 2
	UserStatus_USER_STATUS_BANNED     UserStatus = 3
)

var UserStatus_name = map[int32]string{
	0: "USER_STATUS_INVALID",
	1: "USER_STATUS_REGISTERED",
	2: "USER_STATUS_ACTIVE",
	3: "USER_STATUS_BANNED",
}

var UserStatus_value = map[string]int32{
	"USER_STATUS_INVALID":    0,
	"USER_STATUS_REGISTERED": 1,
	"USER_STATUS_ACTIVE":     2,
	"USER_STATUS_BANNED":     3,
}

func (x UserStatus) String() string {
	return proto.EnumName(UserStatus_name, int32(x))
}

func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_234d831259a1c5d0, []int{0}
}

type User struct {
	Id                   int64            `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" db:"id" `
	Email                string           `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty" db:"email" `
	DisplayName          string           `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty" db:"display_name" `
	Password             string           `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty" db:"password" `
	Status               UserStatus       `protobuf:"varint,5,opt,name=status,proto3,enum=user.UserStatus" json:"status,omitempty" db:"status" `
	CreatedAt            *types.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" db:"created_at" `
	UpdatedAt            *types.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" db:"updated_at" `
	LastLogin            *types.Timestamp `protobuf:"bytes,8,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty" db:"last_login" `
	ChangePassAt         *types.Timestamp `protobuf:"bytes,9,opt,name=change_pass_at,json=changePassAt,proto3" json:"change_pass_at,omitempty" db:"change_pass_at" `
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_234d831259a1c5d0, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetStatus() UserStatus {
	if m != nil {
		return m.Status
	}
	return UserStatus_USER_STATUS_INVALID
}

func (m *User) GetCreatedAt() *types.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *types.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *User) GetLastLogin() *types.Timestamp {
	if m != nil {
		return m.LastLogin
	}
	return nil
}

func (m *User) GetChangePassAt() *types.Timestamp {
	if m != nil {
		return m.ChangePassAt
	}
	return nil
}

type UserResponse struct {
	Id                   int64      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName          string     `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Token                string     `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Status               UserStatus `protobuf:"varint,4,opt,name=status,proto3,enum=user.UserStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_234d831259a1c5d0, []int{1}
}
func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserResponse) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *UserResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *UserResponse) GetStatus() UserStatus {
	if m != nil {
		return m.Status
	}
	return UserStatus_USER_STATUS_INVALID
}

type LoginRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty" validate:"email,required" `
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty" validate:"gte=6,required" `
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_234d831259a1c5d0, []int{2}
}
func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LogoutRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutRequest) Reset()         { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()    {}
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_234d831259a1c5d0, []int{3}
}
func (m *LogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRequest.Unmarshal(m, b)
}
func (m *LogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRequest.Marshal(b, m, deterministic)
}
func (m *LogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRequest.Merge(m, src)
}
func (m *LogoutRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutRequest.Size(m)
}
func (m *LogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRequest proto.InternalMessageInfo

type LogoutResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutResponse) Reset()         { *m = LogoutResponse{} }
func (m *LogoutResponse) String() string { return proto.CompactTextString(m) }
func (*LogoutResponse) ProtoMessage()    {}
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_234d831259a1c5d0, []int{4}
}
func (m *LogoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutResponse.Unmarshal(m, b)
}
func (m *LogoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutResponse.Marshal(b, m, deterministic)
}
func (m *LogoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutResponse.Merge(m, src)
}
func (m *LogoutResponse) XXX_Size() int {
	return xxx_messageInfo_LogoutResponse.Size(m)
}
func (m *LogoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutResponse proto.InternalMessageInfo

type RegisterRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty" validate:"email,required" `
	DisplayName          string   `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty" validate:"gte=3,required" `
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty" validate:"gte=6,required" `
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_234d831259a1c5d0, []int{5}
}
func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterRequest) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type PingRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_234d831259a1c5d0, []int{6}
}
func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

type ChangePasswordRequest struct {
	OldPassword          string   `protobuf:"bytes,1,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword          string   `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty" validate:"gte=6,required" `
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordRequest) Reset()         { *m = ChangePasswordRequest{} }
func (m *ChangePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordRequest) ProtoMessage()    {}
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_234d831259a1c5d0, []int{7}
}
func (m *ChangePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordRequest.Unmarshal(m, b)
}
func (m *ChangePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordRequest.Marshal(b, m, deterministic)
}
func (m *ChangePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordRequest.Merge(m, src)
}
func (m *ChangePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordRequest.Size(m)
}
func (m *ChangePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordRequest proto.InternalMessageInfo

func (m *ChangePasswordRequest) GetOldPassword() string {
	if m != nil {
		return m.OldPassword
	}
	return ""
}

func (m *ChangePasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type ChangePasswordResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordResponse) Reset()         { *m = ChangePasswordResponse{} }
func (m *ChangePasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordResponse) ProtoMessage()    {}
func (*ChangePasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_234d831259a1c5d0, []int{8}
}
func (m *ChangePasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordResponse.Unmarshal(m, b)
}
func (m *ChangePasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordResponse.Marshal(b, m, deterministic)
}
func (m *ChangePasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordResponse.Merge(m, src)
}
func (m *ChangePasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordResponse.Size(m)
}
func (m *ChangePasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordResponse proto.InternalMessageInfo

type ChangeDisplayNameRequest struct {
	DisplayName          string   `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty" validate:"gte=3,required" `
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeDisplayNameRequest) Reset()         { *m = ChangeDisplayNameRequest{} }
func (m *ChangeDisplayNameRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeDisplayNameRequest) ProtoMessage()    {}
func (*ChangeDisplayNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_234d831259a1c5d0, []int{9}
}
func (m *ChangeDisplayNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeDisplayNameRequest.Unmarshal(m, b)
}
func (m *ChangeDisplayNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeDisplayNameRequest.Marshal(b, m, deterministic)
}
func (m *ChangeDisplayNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeDisplayNameRequest.Merge(m, src)
}
func (m *ChangeDisplayNameRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeDisplayNameRequest.Size(m)
}
func (m *ChangeDisplayNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeDisplayNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeDisplayNameRequest proto.InternalMessageInfo

func (m *ChangeDisplayNameRequest) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

type ChangeDisplayNameResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeDisplayNameResponse) Reset()         { *m = ChangeDisplayNameResponse{} }
func (m *ChangeDisplayNameResponse) String() string { return proto.CompactTextString(m) }
func (*ChangeDisplayNameResponse) ProtoMessage()    {}
func (*ChangeDisplayNameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_234d831259a1c5d0, []int{10}
}
func (m *ChangeDisplayNameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeDisplayNameResponse.Unmarshal(m, b)
}
func (m *ChangeDisplayNameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeDisplayNameResponse.Marshal(b, m, deterministic)
}
func (m *ChangeDisplayNameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeDisplayNameResponse.Merge(m, src)
}
func (m *ChangeDisplayNameResponse) XXX_Size() int {
	return xxx_messageInfo_ChangeDisplayNameResponse.Size(m)
}
func (m *ChangeDisplayNameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeDisplayNameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeDisplayNameResponse proto.InternalMessageInfo

type ForgotPasswordRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty" validate:"email,required" `
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgotPasswordRequest) Reset()         { *m = ForgotPasswordRequest{} }
func (m *ForgotPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ForgotPasswordRequest) ProtoMessage()    {}
func (*ForgotPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_234d831259a1c5d0, []int{11}
}
func (m *ForgotPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgotPasswordRequest.Unmarshal(m, b)
}
func (m *ForgotPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgotPasswordRequest.Marshal(b, m, deterministic)
}
func (m *ForgotPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgotPasswordRequest.Merge(m, src)
}
func (m *ForgotPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ForgotPasswordRequest.Size(m)
}
func (m *ForgotPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgotPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForgotPasswordRequest proto.InternalMessageInfo

func (m *ForgotPasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type ForgotPasswordResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgotPasswordResponse) Reset()         { *m = ForgotPasswordResponse{} }
func (m *ForgotPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ForgotPasswordResponse) ProtoMessage()    {}
func (*ForgotPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_234d831259a1c5d0, []int{12}
}
func (m *ForgotPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgotPasswordResponse.Unmarshal(m, b)
}
func (m *ForgotPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgotPasswordResponse.Marshal(b, m, deterministic)
}
func (m *ForgotPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgotPasswordResponse.Merge(m, src)
}
func (m *ForgotPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ForgotPasswordResponse.Size(m)
}
func (m *ForgotPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgotPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ForgotPasswordResponse proto.InternalMessageInfo

type VerifyTokenRequest struct {
	TokenId              string   `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty" validate:"required" `
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyTokenRequest) Reset()         { *m = VerifyTokenRequest{} }
func (m *VerifyTokenRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyTokenRequest) ProtoMessage()    {}
func (*VerifyTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_234d831259a1c5d0, []int{13}
}
func (m *VerifyTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyTokenRequest.Unmarshal(m, b)
}
func (m *VerifyTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyTokenRequest.Marshal(b, m, deterministic)
}
func (m *VerifyTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyTokenRequest.Merge(m, src)
}
func (m *VerifyTokenRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyTokenRequest.Size(m)
}
func (m *VerifyTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyTokenRequest proto.InternalMessageInfo

func (m *VerifyTokenRequest) GetTokenId() string {
	if m != nil {
		return m.TokenId
	}
	return ""
}

func init() {
	proto.RegisterEnum("user.UserStatus", UserStatus_name, UserStatus_value)
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*UserResponse)(nil), "user.UserResponse")
	proto.RegisterType((*LoginRequest)(nil), "user.LoginRequest")
	proto.RegisterType((*LogoutRequest)(nil), "user.LogoutRequest")
	proto.RegisterType((*LogoutResponse)(nil), "user.LogoutResponse")
	proto.RegisterType((*RegisterRequest)(nil), "user.RegisterRequest")
	proto.RegisterType((*PingRequest)(nil), "user.PingRequest")
	proto.RegisterType((*ChangePasswordRequest)(nil), "user.ChangePasswordRequest")
	proto.RegisterType((*ChangePasswordResponse)(nil), "user.ChangePasswordResponse")
	proto.RegisterType((*ChangeDisplayNameRequest)(nil), "user.ChangeDisplayNameRequest")
	proto.RegisterType((*ChangeDisplayNameResponse)(nil), "user.ChangeDisplayNameResponse")
	proto.RegisterType((*ForgotPasswordRequest)(nil), "user.ForgotPasswordRequest")
	proto.RegisterType((*ForgotPasswordResponse)(nil), "user.ForgotPasswordResponse")
	proto.RegisterType((*VerifyTokenRequest)(nil), "user.VerifyTokenRequest")
}

func init() { proto.RegisterFile("modules/user/proto/user.proto", fileDescriptor_234d831259a1c5d0) }

var fileDescriptor_234d831259a1c5d0 = []byte{
	// 1122 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xcf, 0x6e, 0xe3, 0x44,
	0x1c, 0xae, 0xd3, 0x34, 0x9b, 0x4e, 0xd2, 0x34, 0x9d, 0xa6, 0xc1, 0x4d, 0xbb, 0x1b, 0xaf, 0x25,
	0x50, 0x55, 0x6d, 0x13, 0xb6, 0x5d, 0x21, 0x11, 0x09, 0x89, 0xa4, 0x0d, 0x28, 0xa8, 0x54, 0x95,
	0x93, 0x16, 0x09, 0x09, 0x45, 0x93, 0x78, 0xea, 0x5a, 0x24, 0x1e, 0xd7, 0x1e, 0xb7, 0x14, 0x09,
	0x09, 0x38, 0xae, 0xc4, 0x05, 0x4e, 0xbc, 0x01, 0x37, 0x24, 0x1e, 0x02, 0x71, 0xe7, 0xc6, 0x21,
	0x27, 0x2e, 0xdc, 0x56, 0x79, 0x02, 0x34, 0x33, 0x76, 0xec, 0x24, 0xae, 0xa2, 0xc2, 0x25, 0xf1,
	0xcc, 0x7c, 0xbf, 0xef, 0xf7, 0xf7, 0x1b, 0x1b, 0x3c, 0x1d, 0x12, 0xdd, 0x1b, 0x60, 0xb7, 0xea,
	0xb9, 0xd8, 0xa9, 0xda, 0x0e, 0xa1, 0x84, 0x3f, 0x56, 0xf8, 0x23, 0x4c, 0xb2, 0xe7, 0xd2, 0x4b,
	0xc3, 0xa4, 0xd7, 0x5e, 0xaf, 0xd2, 0x27, 0xc3, 0xea, 0xd5, 0xd7, 0xd8, 0x21, 0x8e, 0xd7, 0x33,
	0x0d, 0x5d, 0xc0, 0x7b, 0xde, 0x55, 0x15, 0x7f, 0x45, 0x1d, 0x24, 0x7e, 0x85, 0x61, 0xe9, 0xdd,
	0x45, 0x26, 0xf4, 0xde, 0xc6, 0x2e, 0xff, 0xf5, 0x2d, 0x0e, 0x22, 0x16, 0x06, 0x31, 0x48, 0x08,
	0x65, 0x2b, 0x11, 0x19, 0x7b, 0xf2, 0xe1, 0xbb, 0x06, 0x21, 0xc6, 0x00, 0x57, 0x91, 0x6d, 0x56,
	0x91, 0x65, 0x11, 0x8a, 0xa8, 0x49, 0x2c, 0xd7, 0x3f, 0x7d, 0xc1, 0xff, 0xfa, 0x07, 0x06, 0xb6,
	0x0e, 0xdc, 0x3b, 0x64, 0x18, 0xd8, 0xa9, 0x12, 0x9b, 0x23, 0xe6, 0xd1, 0xea, 0x2f, 0x49, 0x90,
	0xbc, 0x70, 0xb1, 0x03, 0x77, 0x41, 0xc2, 0xd4, 0x65, 0x49, 0x91, 0xf6, 0x96, 0x1b, 0xd9, 0xf1,
	0xa8, 0x9c, 0xd6, 0x7b, 0x35, 0xd5, 0xd4, 0x55, 0x45, 0x4b, 0x98, 0x3a, 0x7c, 0x1b, 0xac, 0xe0,
	0x21, 0x32, 0x07, 0x72, 0x42, 0x91, 0xf6, 0x56, 0x1b, 0xeb, 0xe3, 0x51, 0x39, 0xc3, 0x00, 0x7c,
	0x53, 0x55, 0x34, 0x71, 0x0a, 0xdf, 0x07, 0x59, 0xdd, 0x74, 0xed, 0x01, 0xba, 0xef, 0x5a, 0x68,
	0x88, 0xe5, 0x65, 0x8e, 0x2e, 0x8e, 0x47, 0x65, 0xc8, 0xd0, 0xd1, 0x33, 0x55, 0xd1, 0x32, 0xfe,
	0xfa, 0x0c, 0x0d, 0x31, 0xac, 0x80, 0xb4, 0x8d, 0x5c, 0xf7, 0x8e, 0x38, 0xba, 0x9c, 0xe4, 0x66,
	0x70, 0x3c, 0x2a, 0xe7, 0x98, 0x59, 0xb0, 0xaf, 0x2a, 0xda, 0x04, 0x03, 0x6b, 0x20, 0xe5, 0x52,
	0x44, 0x3d, 0x57, 0x5e, 0x51, 0xa4, 0xbd, 0xdc, 0x61, 0xbe, 0xc2, 0x7b, 0xc7, 0x72, 0x69, 0xf3,
	0xfd, 0x46, 0x7e, 0x3c, 0x2a, 0x67, 0x99, 0xbd, 0xc0, 0xa9, 0x8a, 0xe6, 0x5b, 0xc0, 0x26, 0x00,
	0x7d, 0x07, 0x23, 0x8a, 0xf5, 0x2e, 0xa2, 0x72, 0x4a, 0x91, 0xf6, 0x32, 0x87, 0xf9, 0x0a, 0x6f,
	0x4b, 0xa5, 0x63, 0x0e, 0xb1, 0x4b, 0xd1, 0xd0, 0x6e, 0x14, 0xc6, 0xa3, 0x72, 0x9e, 0xd9, 0x87,
	0x58, 0x55, 0xd1, 0x56, 0xfd, 0x55, 0x9d, 0x32, 0x1a, 0xcf, 0xd6, 0x03, 0x9a, 0x27, 0x8b, 0x68,
	0x42, 0x2c, 0xa3, 0xf1, 0x57, 0x82, 0x66, 0x80, 0x5c, 0xda, 0x1d, 0x10, 0xc3, 0xb4, 0xe4, 0xf4,
	0x22, 0x9a, 0x10, 0xcb, 0x68, 0xd8, 0xea, 0x94, 0x2d, 0xe0, 0x39, 0xc8, 0xf5, 0xaf, 0x91, 0x65,
	0xe0, 0x2e, 0xab, 0x11, 0x8b, 0x68, 0xf5, 0x01, 0x2a, 0x79, 0x3c, 0x2a, 0x17, 0x78, 0x62, 0x53,
	0x78, 0x55, 0xd1, 0xb2, 0x62, 0xe7, 0x1c, 0xb9, 0x6e, 0x9d, 0xd6, 0xd6, 0xfe, 0x78, 0xb3, 0x2d,
	0xfd, 0xf5, 0x66, 0x7b, 0x85, 0x55, 0xd6, 0x55, 0xbf, 0x93, 0x40, 0x96, 0x95, 0x57, 0xc3, 0xae,
	0x4d, 0x2c, 0x17, 0xc3, 0x5c, 0x38, 0x32, 0x7c, 0x48, 0x9e, 0xcf, 0x74, 0x9f, 0xcf, 0xca, 0x74,
	0x97, 0x0b, 0x60, 0x85, 0x92, 0x2f, 0xb1, 0x25, 0x26, 0x43, 0x13, 0x0b, 0xb8, 0x37, 0xe9, 0x65,
	0x32, 0xbe, 0x97, 0x41, 0xe7, 0xd4, 0x6f, 0x25, 0x90, 0xe5, 0xe9, 0x6a, 0xf8, 0xc6, 0xc3, 0x2e,
	0x85, 0xaf, 0x82, 0xc1, 0x94, 0xf8, 0xcc, 0x3c, 0x1b, 0x8f, 0xca, 0xa5, 0x5b, 0x34, 0x30, 0x59,
	0x71, 0xfd, 0xf1, 0x7c, 0xe1, 0xe0, 0x1b, 0xcf, 0x74, 0xb0, 0x1e, 0xce, 0x69, 0x2d, 0x32, 0x6c,
	0x89, 0x38, 0x43, 0x83, 0xe2, 0x0f, 0xde, 0x8b, 0x1a, 0x4e, 0xf0, 0xea, 0x3a, 0x58, 0x3b, 0x25,
	0x06, 0xf1, 0xa8, 0x1f, 0x82, 0x9a, 0x07, 0xb9, 0x60, 0x43, 0x14, 0x46, 0xfd, 0x5d, 0x02, 0xeb,
	0x1a, 0x36, 0x4c, 0x97, 0xb2, 0x6a, 0xfd, 0x9f, 0x40, 0xeb, 0x71, 0x25, 0x8d, 0x0b, 0xf6, 0x28,
	0x6a, 0x3c, 0x55, 0xf2, 0x68, 0xae, 0xcb, 0x8f, 0xcc, 0x75, 0x0d, 0x64, 0xce, 0x4d, 0xcb, 0x08,
	0x32, 0xfd, 0x06, 0x6c, 0x1d, 0x4f, 0x06, 0x84, 0x01, 0x82, 0xe4, 0x9e, 0x83, 0x2c, 0x19, 0xe8,
	0xdd, 0x89, 0x1f, 0x49, 0x74, 0x9e, 0x0c, 0xf4, 0x00, 0xc9, 0x32, 0xb1, 0xf0, 0x5d, 0xf7, 0x91,
	0x65, 0xcf, 0x58, 0xf8, 0x2e, 0xa0, 0x50, 0x65, 0x50, 0x9c, 0x75, 0xef, 0x17, 0xfc, 0x0b, 0x20,
	0x8b, 0x93, 0x93, 0x30, 0xf1, 0x20, 0xb6, 0xd9, 0x12, 0x4a, 0x8f, 0x2e, 0xa1, 0xba, 0x03, 0xb6,
	0x63, 0xe8, 0x7d, 0xdf, 0x9f, 0x82, 0xad, 0x8f, 0x88, 0x63, 0x10, 0x3a, 0x5b, 0x94, 0xff, 0xd4,
	0x71, 0x96, 0xe4, 0x2c, 0x9d, 0xef, 0xa8, 0x05, 0xe0, 0x25, 0x76, 0xcc, 0xab, 0xfb, 0x0e, 0x13,
	0x4d, 0xe0, 0xe5, 0x08, 0xa4, 0xb9, 0x88, 0xba, 0xbe, 0x14, 0x57, 0x85, 0xbc, 0x43, 0x47, 0x11,
	0x17, 0x4f, 0x38, 0xb2, 0xa5, 0xef, 0xdf, 0x00, 0x10, 0x8a, 0x0b, 0xbe, 0x05, 0x36, 0x2f, 0xda,
	0x4d, 0xad, 0xdb, 0xee, 0xd4, 0x3b, 0x17, 0xed, 0x6e, 0xeb, 0xec, 0xb2, 0x7e, 0xda, 0x3a, 0xc9,
	0x2f, 0xc1, 0x12, 0x28, 0x46, 0x0f, 0xb4, 0xe6, 0xc7, 0xad, 0x76, 0xa7, 0xa9, 0x35, 0x4f, 0xf2,
	0x12, 0x2c, 0x02, 0x18, 0x3d, 0xab, 0x1f, 0x77, 0x5a, 0x97, 0xcd, 0x7c, 0x62, 0x76, 0xbf, 0x51,
	0x3f, 0x3b, 0x6b, 0x9e, 0xe4, 0x97, 0x0f, 0xff, 0x49, 0xf9, 0x3e, 0xef, 0x5d, 0x8a, 0x87, 0xf0,
	0x13, 0xb0, 0x22, 0xae, 0x2d, 0x28, 0xb4, 0x1e, 0x15, 0x75, 0x09, 0x86, 0xfa, 0x9f, 0x64, 0xbf,
	0xfd, 0xfd, 0x9f, 0x7f, 0xff, 0x94, 0xd8, 0x54, 0x73, 0xd5, 0xdb, 0x97, 0xe2, 0x8d, 0xcd, 0xef,
	0xc0, 0x9a, 0xb4, 0x0f, 0x4d, 0x90, 0x12, 0x02, 0x84, 0x9b, 0x13, 0xb2, 0x50, 0x9f, 0xa5, 0xc2,
	0xf4, 0xa6, 0xcf, 0xf7, 0xea, 0xc7, 0x7a, 0xb1, 0x57, 0x00, 0x10, 0xe4, 0xea, 0x1e, 0xbd, 0xc6,
	0x16, 0x35, 0xfb, 0xfc, 0xc5, 0x08, 0x97, 0x5e, 0xff, 0x5a, 0x5a, 0xe2, 0xce, 0x36, 0xe0, 0x7a,
	0xd4, 0x19, 0x73, 0xd0, 0x06, 0xe9, 0x40, 0xd8, 0x70, 0x4b, 0xf0, 0xce, 0x08, 0x3d, 0x36, 0xf8,
	0x5d, 0xce, 0x57, 0x54, 0x37, 0x26, 0x7c, 0x8e, 0x6f, 0xc5, 0xe2, 0x47, 0x20, 0xc9, 0x54, 0x06,
	0x37, 0x84, 0x65, 0x44, 0x71, 0xb1, 0x64, 0x87, 0x8b, 0x23, 0x5f, 0x87, 0x6b, 0x13, 0x4f, 0x36,
	0xa3, 0xfe, 0x0c, 0x64, 0x22, 0xb3, 0x03, 0x65, 0x41, 0x3b, 0x3f, 0x4e, 0xb1, 0x0e, 0x4b, 0x9c,
	0xb3, 0xa0, 0x86, 0xd5, 0xb8, 0xe5, 0x86, 0x2c, 0xf6, 0x1f, 0x24, 0x90, 0x9b, 0x16, 0x25, 0xdc,
	0x11, 0x14, 0xb1, 0x37, 0x45, 0x69, 0x37, 0xfe, 0xd0, 0xf7, 0xf4, 0xe1, 0xe2, 0xd4, 0x9e, 0xaa,
	0xf2, 0x24, 0x0c, 0xf1, 0xb6, 0xaa, 0x06, 0x77, 0x0a, 0x8b, 0xe7, 0x67, 0x09, 0x6c, 0xcc, 0x69,
	0x15, 0x3e, 0x8b, 0x7a, 0x9d, 0xbf, 0x23, 0x4a, 0xe5, 0x07, 0xcf, 0xfd, 0xc0, 0x8e, 0x17, 0x07,
	0xa6, 0xa8, 0x3b, 0xb3, 0x81, 0xf9, 0x77, 0x08, 0xbb, 0x76, 0x58, 0x6c, 0x06, 0xc8, 0x4d, 0x4b,
	0x3b, 0x28, 0x55, 0xec, 0xfd, 0x11, 0x94, 0xea, 0x81, 0xdb, 0x60, 0xbe, 0x29, 0x57, 0x1c, 0x58,
	0x93, 0xf6, 0x1b, 0xef, 0xbc, 0xfe, 0x6d, 0x7b, 0x19, 0x21, 0x04, 0xd2, 0x7d, 0x32, 0xe4, 0x2c,
	0x8d, 0x55, 0xd6, 0xd1, 0x73, 0xf6, 0xc9, 0x77, 0x2e, 0x7d, 0x9e, 0x62, 0x5b, 0x76, 0xaf, 0x97,
	0xe2, 0xdf, 0x80, 0x47, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0xf3, 0xb9, 0x8e, 0xda, 0x0a, 0x0b,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserSystemClient is the client API for UserSystem service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserSystemClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*UserResponse, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*UserResponse, error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*UserResponse, error)
	VerifyToken(ctx context.Context, in *VerifyTokenRequest, opts ...grpc.CallOption) (*UserResponse, error)
	ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error)
	ChangeDisplayName(ctx context.Context, in *ChangeDisplayNameRequest, opts ...grpc.CallOption) (*ChangeDisplayNameResponse, error)
	ForgotPassword(ctx context.Context, in *ForgotPasswordRequest, opts ...grpc.CallOption) (*ForgotPasswordResponse, error)
}

type userSystemClient struct {
	cc *grpc.ClientConn
}

func NewUserSystemClient(cc *grpc.ClientConn) UserSystemClient {
	return &userSystemClient{cc}
}

func (c *userSystemClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/user.UserSystem/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSystemClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, "/user.UserSystem/Logout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSystemClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/user.UserSystem/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSystemClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/user.UserSystem/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSystemClient) VerifyToken(ctx context.Context, in *VerifyTokenRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/user.UserSystem/VerifyToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSystemClient) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error) {
	out := new(ChangePasswordResponse)
	err := c.cc.Invoke(ctx, "/user.UserSystem/ChangePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSystemClient) ChangeDisplayName(ctx context.Context, in *ChangeDisplayNameRequest, opts ...grpc.CallOption) (*ChangeDisplayNameResponse, error) {
	out := new(ChangeDisplayNameResponse)
	err := c.cc.Invoke(ctx, "/user.UserSystem/ChangeDisplayName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSystemClient) ForgotPassword(ctx context.Context, in *ForgotPasswordRequest, opts ...grpc.CallOption) (*ForgotPasswordResponse, error) {
	out := new(ForgotPasswordResponse)
	err := c.cc.Invoke(ctx, "/user.UserSystem/ForgotPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserSystemServer is the server API for UserSystem service.
type UserSystemServer interface {
	Login(context.Context, *LoginRequest) (*UserResponse, error)
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	Register(context.Context, *RegisterRequest) (*UserResponse, error)
	Ping(context.Context, *PingRequest) (*UserResponse, error)
	VerifyToken(context.Context, *VerifyTokenRequest) (*UserResponse, error)
	ChangePassword(context.Context, *ChangePasswordRequest) (*ChangePasswordResponse, error)
	ChangeDisplayName(context.Context, *ChangeDisplayNameRequest) (*ChangeDisplayNameResponse, error)
	ForgotPassword(context.Context, *ForgotPasswordRequest) (*ForgotPasswordResponse, error)
}

func RegisterUserSystemServer(s *grpc.Server, srv UserSystemServer) {
	s.RegisterService(&_UserSystem_serviceDesc, srv)
}

func _UserSystem_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSystemServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserSystem/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSystemServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSystem_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSystemServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserSystem/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSystemServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSystem_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSystemServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserSystem/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSystemServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSystem_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSystemServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserSystem/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSystemServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSystem_VerifyToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSystemServer).VerifyToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserSystem/VerifyToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSystemServer).VerifyToken(ctx, req.(*VerifyTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSystem_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSystemServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserSystem/ChangePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSystemServer).ChangePassword(ctx, req.(*ChangePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSystem_ChangeDisplayName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeDisplayNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSystemServer).ChangeDisplayName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserSystem/ChangeDisplayName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSystemServer).ChangeDisplayName(ctx, req.(*ChangeDisplayNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSystem_ForgotPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForgotPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSystemServer).ForgotPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserSystem/ForgotPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSystemServer).ForgotPassword(ctx, req.(*ForgotPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserSystem_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserSystem",
	HandlerType: (*UserSystemServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _UserSystem_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _UserSystem_Logout_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _UserSystem_Register_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _UserSystem_Ping_Handler,
		},
		{
			MethodName: "VerifyToken",
			Handler:    _UserSystem_VerifyToken_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _UserSystem_ChangePassword_Handler,
		},
		{
			MethodName: "ChangeDisplayName",
			Handler:    _UserSystem_ChangeDisplayName_Handler,
		},
		{
			MethodName: "ForgotPassword",
			Handler:    _UserSystem_ForgotPassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "modules/user/proto/user.proto",
}
