// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: modules/user/proto/user.proto

package userpb

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/gogo/protobuf/gogoproto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "github.com/fzerorubigd/protobuf/extra"
	_ "github.com/fzerorubigd/protobuf/types"
	elbix_dev_engine_pkg_postgres_model "elbix.dev/engine/pkg/postgres/model"
	time "time"
	github_com_fzerorubigd_protobuf_types "github.com/fzerorubigd/protobuf/types"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

const (
	UserSchema    = "aaa"
	UserTable     = "users"
	UserTableFull = UserSchema + "." + UserTable
)

type Manager struct {
	elbix_dev_engine_pkg_postgres_model.Manager
}

func NewManager() *Manager {
	return &Manager{}
}

func NewManagerFromTransaction(tx elbix_dev_engine_pkg_postgres_model.DBX) (*Manager, error) {
	m := &Manager{}
	err := m.Hijack(tx)

	if err != nil {
		return nil, err
	}

	return m, nil
}

/*
main.modelData{
    table:     "users",
    schema:    "aaa",
    model:     "User",
    receiver:  "u",
    dbFields:  {"id", "email", "display_name", "password", "status", "created_at", "updated_at", "last_login"},
    goFields:  {"Id", "Email", "DisplayName", "Password", "Status", "CreatedAt", "UpdatedAt", "LastLogin"},
    types:     {},
    createdAt: true,
    updatedAt: true,
    hasID:     true,
}
*/

func (m *Manager) CreateUser(ctx context.Context, u *User) error {
	now := time.Now()
	u.CreatedAt = github_com_fzerorubigd_protobuf_types.TimestampProto(now)
	u.UpdatedAt = github_com_fzerorubigd_protobuf_types.TimestampProto(now)
	func(in interface{}) {
		if o, ok := in.(interface{ PreInsert() }); ok {
			o.PreInsert()
		}
	}(u)
	q := `INSERT INTO aaa.users(email, display_name, password, status, created_at, updated_at, last_login) VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id`
	row := m.GetDbMap().QueryRowxContext(ctx, q, u.Email, u.DisplayName, u.Password, u.Status, u.CreatedAt, u.UpdatedAt, u.LastLogin)
	return row.Scan(&u.Id)
}

func (m *Manager) UpdateUser(ctx context.Context, u *User) error {
	var err error
	now := time.Now()
	u.UpdatedAt = github_com_fzerorubigd_protobuf_types.TimestampProto(now)
	func(in interface{}) {
		if o, ok := in.(interface{ PreUpdate() }); ok {
			o.PreUpdate()
		}
	}(u)
	q := `UPDATE aaa.users SET email = $1, display_name = $2, password = $3, status = $4, created_at = $5, updated_at = $6, last_login = $7 WHERE id = $8`
	_, err = m.GetDbMap().ExecContext(ctx, q, u.Email, u.DisplayName, u.Password, u.Status, u.CreatedAt, u.UpdatedAt, u.LastLogin, u.Id)
	return err
}

func (m *Manager) GetUserByPrimary(ctx context.Context, id int64) (*User, error) {
	q := `SELECT id, email, display_name, password, status, created_at, updated_at, last_login FROM aaa.users WHERE id = $1`
	row := m.GetDbMap().QueryRowxContext(ctx, q, id)

	return m.scanUser(row)
}

func (m *Manager) scanUser(row elbix_dev_engine_pkg_postgres_model.Scanner, extra ...interface{}) (*User, error) {
	var u User
	all := append([]interface{}{&u.Id, &u.Email, &u.DisplayName, &u.Password, &u.Status, &u.CreatedAt, &u.UpdatedAt, &u.LastLogin}, extra...)
	err := row.Scan(all...)
	if err != nil {
		return nil, err
	}
	return &u, nil
}

func (m *Manager) getUserFields() []string {
	return []string{"id", "email", "display_name", "password", "status", "created_at", "updated_at", "last_login"}
}
