// Code generated by protoc-gen-grpchan. DO NOT EDIT.
// source: modules/user/proto/user.proto

package userpb

import "github.com/fullstorydev/grpchan"
import "golang.org/x/net/context"
import "google.golang.org/grpc"

func RegisterHandlerUserSystem(reg grpchan.ServiceRegistry, srv UserSystemServer) {
	reg.RegisterService(&_UserSystem_serviceDesc, srv)
}

type userSystemChannelClient struct {
	ch grpchan.Channel
}

func NewUserSystemChannelClient(ch grpchan.Channel) UserSystemClient {
	return &userSystemChannelClient{ch: ch}
}

func (c *userSystemChannelClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.ch.Invoke(ctx, "/user.UserSystem/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSystemChannelClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*NoopResponse, error) {
	out := new(NoopResponse)
	err := c.ch.Invoke(ctx, "/user.UserSystem/Logout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}
