// Code generated by swagger-to-go. DO NOT EDIT.
package miscpb

import (
	"encoding/json"

	"elbix.dev/engine/pkg/assert"
	"elbix.dev/engine/pkg/grpcgw"
)

const paths = "{\"/v1/misc/health\":{\"get\":{\"operationId\":\"Health\",\"responses\":{\"200\":{\"description\":\"A successful response.\",\"schema\":{\"$ref\":\"#/definitions/miscHealthResponse\"}}},\"tags\":[\"MiscSystem\"]}},\"/v1/misc/version\":{\"get\":{\"operationId\":\"Version\",\"responses\":{\"200\":{\"description\":\"A successful response.\",\"schema\":{\"$ref\":\"#/definitions/miscVersionResponse\"}}},\"tags\":[\"MiscSystem\"]}}}"
const definitions = "{\"miscHealthResponse\":{\"type\":\"object\"},\"miscVersionResponse\":{\"properties\":{\"build_date\":{\"format\":\"date-time\",\"type\":\"string\"},\"commit_date\":{\"format\":\"date-time\",\"type\":\"string\"},\"commit_hash\":{\"type\":\"string\"},\"count\":{\"format\":\"int64\",\"type\":\"string\"},\"short_hash\":{\"type\":\"string\"}},\"type\":\"object\"}}"

func init() {
	var (
		p = make(map[string]interface{})
		d = make(map[string]interface{})
	)

	assert.Nil(json.Unmarshal([]byte(paths), &p))
	assert.Nil(json.Unmarshal([]byte(definitions), &d))

	grpcgw.RegisterSwagger(p, d)
}

