// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: modules/misc/proto/misc.proto

package miscpb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import types "github.com/gogo/protobuf/types"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type VersionResponse struct {
	CommitHash           string           `protobuf:"bytes,1,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`
	ShortHash            string           `protobuf:"bytes,2,opt,name=short_hash,json=shortHash,proto3" json:"short_hash,omitempty"`
	BuildDate            *types.Timestamp `protobuf:"bytes,3,opt,name=build_date,json=buildDate" json:"build_date,omitempty"`
	CommitDate           *types.Timestamp `protobuf:"bytes,4,opt,name=commit_date,json=commitDate" json:"commit_date,omitempty"`
	Count                int64            `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *VersionResponse) Reset()         { *m = VersionResponse{} }
func (m *VersionResponse) String() string { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()    {}
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_misc_5fd87211a1e5b5ad, []int{0}
}
func (m *VersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionResponse.Unmarshal(m, b)
}
func (m *VersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionResponse.Marshal(b, m, deterministic)
}
func (dst *VersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionResponse.Merge(dst, src)
}
func (m *VersionResponse) XXX_Size() int {
	return xxx_messageInfo_VersionResponse.Size(m)
}
func (m *VersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VersionResponse proto.InternalMessageInfo

func (m *VersionResponse) GetCommitHash() string {
	if m != nil {
		return m.CommitHash
	}
	return ""
}

func (m *VersionResponse) GetShortHash() string {
	if m != nil {
		return m.ShortHash
	}
	return ""
}

func (m *VersionResponse) GetBuildDate() *types.Timestamp {
	if m != nil {
		return m.BuildDate
	}
	return nil
}

func (m *VersionResponse) GetCommitDate() *types.Timestamp {
	if m != nil {
		return m.CommitDate
	}
	return nil
}

func (m *VersionResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type VersionRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionRequest) Reset()         { *m = VersionRequest{} }
func (m *VersionRequest) String() string { return proto.CompactTextString(m) }
func (*VersionRequest) ProtoMessage()    {}
func (*VersionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_misc_5fd87211a1e5b5ad, []int{1}
}
func (m *VersionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionRequest.Unmarshal(m, b)
}
func (m *VersionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionRequest.Marshal(b, m, deterministic)
}
func (dst *VersionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionRequest.Merge(dst, src)
}
func (m *VersionRequest) XXX_Size() int {
	return xxx_messageInfo_VersionRequest.Size(m)
}
func (m *VersionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VersionRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*VersionResponse)(nil), "misc.VersionResponse")
	proto.RegisterType((*VersionRequest)(nil), "misc.VersionRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MiscSystemClient is the client API for MiscSystem service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MiscSystemClient interface {
	Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error)
}

type miscSystemClient struct {
	cc *grpc.ClientConn
}

func NewMiscSystemClient(cc *grpc.ClientConn) MiscSystemClient {
	return &miscSystemClient{cc}
}

func (c *miscSystemClient) Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, "/misc.MiscSystem/Version", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MiscSystemServer is the server API for MiscSystem service.
type MiscSystemServer interface {
	Version(context.Context, *VersionRequest) (*VersionResponse, error)
}

func RegisterMiscSystemServer(s *grpc.Server, srv MiscSystemServer) {
	s.RegisterService(&_MiscSystem_serviceDesc, srv)
}

func _MiscSystem_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiscSystemServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/misc.MiscSystem/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiscSystemServer).Version(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MiscSystem_serviceDesc = grpc.ServiceDesc{
	ServiceName: "misc.MiscSystem",
	HandlerType: (*MiscSystemServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Version",
			Handler:    _MiscSystem_Version_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "modules/misc/proto/misc.proto",
}

func init() { proto.RegisterFile("modules/misc/proto/misc.proto", fileDescriptor_misc_5fd87211a1e5b5ad) }

var fileDescriptor_misc_5fd87211a1e5b5ad = []byte{
	// 336 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x51, 0xcd, 0x4a, 0xf3, 0x40,
	0x14, 0x25, 0xfd, 0xfb, 0xbe, 0xdc, 0x82, 0x96, 0xa1, 0x42, 0x08, 0x96, 0x96, 0xae, 0xba, 0x31,
	0xc1, 0xba, 0x12, 0x77, 0xc5, 0x85, 0x1b, 0xa1, 0x44, 0x71, 0xe1, 0xc2, 0x32, 0x49, 0xc7, 0x64,
	0xa0, 0x93, 0x1b, 0x7b, 0x67, 0x0a, 0x6e, 0x7d, 0x05, 0x1f, 0xcd, 0x07, 0x70, 0xe3, 0x83, 0x48,
	0x66, 0xd2, 0x82, 0x6e, 0xdc, 0x9d, 0x39, 0x3f, 0xb9, 0xe7, 0xe6, 0xc2, 0x48, 0xe1, 0xda, 0x6c,
	0x04, 0xc5, 0x4a, 0x52, 0x16, 0x57, 0x5b, 0xd4, 0x68, 0x61, 0x64, 0x21, 0xeb, 0xd4, 0x38, 0x3c,
	0xcb, 0xa5, 0x2e, 0x4c, 0x1a, 0x65, 0xa8, 0xe2, 0x1c, 0x73, 0x74, 0xbe, 0xd4, 0x3c, 0xdb, 0x97,
	0x0b, 0xd5, 0xc8, 0x85, 0xc2, 0xd3, 0x1c, 0x31, 0xdf, 0x88, 0x98, 0x57, 0x32, 0xe6, 0x65, 0x89,
	0x9a, 0x6b, 0x89, 0x25, 0x35, 0xea, 0xb8, 0x51, 0x0f, 0xdf, 0xd0, 0x52, 0x09, 0xd2, 0x5c, 0x55,
	0xce, 0x30, 0xfd, 0xf4, 0xe0, 0xf8, 0x41, 0x6c, 0x49, 0x62, 0x99, 0x08, 0xaa, 0xb0, 0x24, 0xc1,
	0xc6, 0xd0, 0xcf, 0x50, 0x29, 0xa9, 0x57, 0x05, 0xa7, 0x22, 0xf0, 0x26, 0xde, 0xcc, 0x4f, 0xc0,
	0x51, 0x37, 0x9c, 0x0a, 0x36, 0x02, 0xa0, 0x02, 0xb7, 0x8d, 0xde, 0xb2, 0xba, 0x6f, 0x19, 0x2b,
	0x5f, 0x02, 0xa4, 0x46, 0x6e, 0xd6, 0xab, 0x35, 0xd7, 0x22, 0x68, 0x4f, 0xbc, 0x59, 0x7f, 0x1e,
	0x46, 0xae, 0x49, 0xb4, 0x6f, 0x12, 0xdd, 0xef, 0x9b, 0x24, 0xbe, 0x75, 0x5f, 0x73, 0x2d, 0xd8,
	0xd5, 0x61, 0xb4, 0xcd, 0x76, 0xfe, 0xcc, 0x36, 0xb5, 0x6c, 0x78, 0x08, 0xdd, 0x0c, 0x4d, 0xa9,
	0x83, 0xee, 0xc4, 0x9b, 0xb5, 0x13, 0xf7, 0x98, 0x0e, 0xe0, 0xe8, 0xb0, 0xe0, 0x8b, 0x11, 0xa4,
	0xe7, 0x4f, 0x00, 0xb7, 0x92, 0xb2, 0xbb, 0x57, 0xd2, 0x42, 0xb1, 0x25, 0xfc, 0x6b, 0x74, 0x36,
	0x8c, 0xec, 0x35, 0x7e, 0xda, 0xc3, 0x93, 0x5f, 0xac, 0xfb, 0x4b, 0xd3, 0xe0, 0xed, 0xe3, 0xeb,
	0xbd, 0xc5, 0xd8, 0x20, 0xde, 0x9d, 0xbb, 0x83, 0xee, 0x9c, 0x63, 0x31, 0x86, 0xff, 0x19, 0x2a,
	0x9b, 0x5a, 0xf8, 0xf5, 0xa4, 0x65, 0xdd, 0x7b, 0xe9, 0x3d, 0xf6, 0x6a, 0xaa, 0x4a, 0xd3, 0x9e,
	0x5d, 0xe4, 0xe2, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x56, 0x37, 0x2a, 0x99, 0x10, 0x02, 0x00, 0x00,
}
